### ISSUE TITLE
Possible reason for causing crash in App

### ISSUE THREAD

**Issue by SagarSrivastava10** [snaksh/application#7]
HAMS - 08 upon completely uploading all it's files , was still trying to upload files but files were not uploading , upon checking the HAMS folder, only the log files were present. Probably trying to upload the log files and failing to do so was causing the app to crash ?

**Comment by SagarSrivastava10** [comment]
Upload the logging files in another folder . Abhishek please make the changes to the app .

**Comment by b-abv** [comment]
Now log files are dumped into Downloads/HAMS_LOGS
